### ISSUE TITLE
Unit tests and documentation for relationships

### ISSUE THREAD

**Issue by samatcd** [phpsa/laravel-api-controller#110]
1. Create unit tests for relationship handling:
   - [ ] Consistent behaviour across different relationship types, including polymorphs
   - [ ] Pivot table values handled appropriately
   - [ ] `sync` strategy vs its inverse
   - [ ] Creating related records
   - [ ] Deleting related records
   - [ ] Filtering the parent models on values in related records

2. Ensure documentation in `README.md` is accurate for the desired relationship behaviour, including examples.

Note this issue is not to change any existing behaviour, but to test if the existing behaviour meets the expected / documented behaviours. We'll create follow-up issues for any failing tests, and plan any required changes in behaviour, as they could have wide effects on existing projects.

**Comment by phpsa** [comment]
Moved to internal project
