### ISSUE TITLE
The "soft-deletes" option does not exist.

### ISSUE THREAD

**Issue by dryas** [phpsa/laravel-api-controller#112]
Hey, I'm trying to get this Plugin working with Laravel 10. When I try to create a controller with Artisan I always get the error:

The "soft-deletes" option does not exist.

and no Controller get's created. Does anyone has an idea what I'm doing wrong? Not sure if this is a bug or a fault on my side TBH.

The command I'm using:

php artisan make:api:controller ManufacturerController

Thanks a lot,

Ben

**Comment by phpsa** [comment]
Hi
Thanks for the report, 
I will have a patch for this within the next day or so.

**Comment by phpsa** [comment]
Sorry for the delay, This will be released today
