### ISSUE TITLE
ApiResource can't be used effectively with `respondWithResource`

### ISSUE THREAD

**Issue by samatcd** [phpsa/laravel-api-controller#34]
Using `respondWithResource` on an ad-hoc data structure doesn't work, as `ApiResource` will always filter out all keys due to allow fields implementation.

`$this->respondWithResource(ApiResource::class, ['prop' => 'value'], 200);`

I've worked around this in my project by using the following basic resource for any ad-hoc replies, which doesn't filter fields, but it'd be nice to have an official / baked in way of doing this.

```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Phpsa\LaravelApiController\Http\Resources\Contracts\CaseFormat;

class ApiBasicResource extends JsonResource
{
    use CaseFormat;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $data = parent::toArray($request);

        return $this->caseFormat($request, $data);
    }
}
```

**Comment by phpsa** [comment]
Resolved by Release 1.1.1-rc.1
