### ISSUE TITLE
Method for deleting related data

### ISSUE THREAD

**Issue by timack** [phpsa/laravel-api-controller#88]
Would be good to have a way delete related data through the API 

1. DELETE with body:
eg: to delete a users 'device'     
```
"devices": [
        {"id" : "ABC123EFG456"}
]
```
2. DELETE via route for sub resource - ie. DELETE {url}/{resource}/{resource_id}/{relationship}/{related_id}

**Comment by phpsa** [comment]
Would suggest sticking to the CRUD single use per controller methodology and create a userDevices endpoint to deal with this, you can then use the request / policy to make sure it is secure,

if you are trying to send through a list of devices as part of a full body then the sync methodology would be better.
