### ISSUE TITLE
Handling of null values when saving related data

### ISSUE THREAD

**Issue by samatcd** [phpsa/laravel-api-controller#98]
The API throws an error when saving a related record with a `null` value instead of an array of related records.

E.g., Consider I have `User` and `Availability` models.
A User is related to Availability.

If I make a request, E.g., 

```
{
  "email": "test@test.com",
  "availability": null,
}
```

A 500 error is thrown.

We should instead try to unlink all related if `sync[availability]` is set, or otherwise ignore an empty value.

**Comment by timack** [comment]
@samatcd I've no budget. Would this be chargeable? Also I'm not really familiar with the innards of this library so might take me a while.

**Comment by phpsa** [comment]
this has been resolved
